### ISSUE TITLE
Unable to load web app

### ISSUE THREAD

**Issue by prachinav** [SE-Group-95/campus-job-review-system#14]
Getting this error when running deploy.sh

```
Error: While importing 'crudapp', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 234, in locate_app
    __import__(module_name)
  File "/app/crudapp.py", line 1, in <module>
    from app import app, db
  File "/app/app/__init__.py", line 1, in <module>
    from app import routes, models
  File "/app/app/routes.py", line 1, in <module>
    from app.services.job_fetcher import fetch_job_listings
  File "/app/app/services/job_fetcher.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by 22SiD** [comment]
Containerisation solved the issue
